### ISSUE TITLE
schematic review

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Almazny#2]
@shanasz 
- [x] use LDOs from other designs (Urukul, Phaser, Zotino, Fastino. The LDOs are known to be unstable.
- [x] the Mirny has a new connector with 16 GPIOs
- [x] I'm not sure standard components (C14,C17,C18) would work for 12GHz. Did you check their resonant frequency?
- [x] I'm not sure if resistive divider would work for 12GHz. it needs simulation, but safer would be to place integrated one
- [ ] SPI levels are 3V3. Use HCT595 that has LVTTL levels compatible with LVCMOS signaling. 
- [ ] Are C16/C26/C24 sufficient for the decoupling of such high RF?
- [x] run LTM8074 from 12V. 7V5 is a low noise rail. This inverting converter is quite unfortunate, It has issues with light loading and injects a lot of noise to the input rail. I would recommend using one from Shuttler design which works as a real inverting one.
- [ ] consider supplying HMC424 from positive levels. Tie VCC to GND and GND to +5V. The logic levels would be simply inverted.
- [x] the attenuator control levels are wrong. 
![obraz](https://user-images.githubusercontent.com/4325054/94861824-668b0a80-0438-11eb-96b0-98b83e5e6a5a.png)

**Comment by shanasz** [comment]
So:
AD 3 : In case of DC-blocking capacitor, we need the resonance to carry the signal. Generally 0402 and 0201 capacitors can be used up to 10...15 GHz introducing loss <1dB. Few RF coupling caps are removed because amplifier is internally coupled and attenuator is DC-compatible). The one protecting switch output remained, I used AVX 1pF 0201 ACCU-P (AVX RF-series) capacitor. Other option was 10pF Skyworks Metal Insulator Silicon (MIS) chip capacitor for low loss (these DC-blocks operate up to 26GHz) but it would be a bit overengineering. 
AD 7 : inverting converter changed to TPS63710DRR, supplied from P12V0.
AD 1: LDOs changed to LT4035 and LT3094
AD 2 : Ok, changed.
AD 5 : Ok, changed. Logic levels corrected.
AD 6 : VCC polygon to GND plane capacitance will decouple higher frequencies.  
AD 4: Pi attenuator is changed to integrated. Although RF resistors <100R operate up to 20GHz or more, integrated is more practical.
AD 8 and 9 : Levels corrected. Are You sure about supplying HMC424 from positive? I think it may be risky.

**Comment by gkasprow** [comment]
AD3: IN case of caps, the circuit must be wideband, I see no advantage of using resonant modes.
There are wideband caps available ( i.e. ATC530L104KT16T) 

AD8. Why it is risky? inputs and outputs are AC coupled anyway.  It does not matter how you swap the supplies.
Let's leave as it is now. It's easier to provide correct GND in such way.

**Comment by shanasz** [comment]
AD3: I may have expressed myself wrongly, I called "resonance" the pass-band of series capacitor between capacitive reflection and inductive reflection, I didnt mean to use higher resonances.

AD8. Yees, but in this case I would have to connect 4 GND pins and central pad to a  5V-supplied polygon coupled with ground plane and therefore force signal to change reference planes - of course it is possible but if I prefer to avoid it. Additionally now DC component is equal 0 nad I can remove DC-blocking capacitors, from signal path.
